### PR TITLE
child-shell

### LINKED ISSUE #84: MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit
The code will cause this.streams.stderr to repeatedly listen for the same event:
```javascript
const Shell = require("node-powershell");

const test = async () => {
  const ps = new Shell({
    executionPolicy: "Bypass",
    noProfile: true
  })
  for (let index = 0; index < 10; index++) {
    ps.addCommand(`echo ${index}`)
    const res = await ps.invoke()
    console.log("im index and res: %n %s", index, res)
  }
}
 test()
```
image

https://github.com/rannn505/node-powershell/blob/b0a0f7f33f7c0b07351e875007e97a20d217b420/lib/Shell.js#L174-L228

I have noticed that every time you run the invoke function, you will recreate the ShellStreamBuffer instance, this should be optimizable.
https://github.com/rannn505/node-powershell/blob/b0a0f7f33f7c0b07351e875007e97a20d217b420/lib/Shell.js#L180

### LINKED ISSUE #92: could not handle error event which emit under constructor.
[Shell.js](https://github.com/rannn505/node-powershell/blob/HEAD/lib/Shell.js#L70)
```js
    if(!this.pid) {
      this.emit('error', new PS_PROC_ERROR());
    }
    proc.once('error', () => {
      this.emit('error', new PS_PROC_ERROR());
    });
```
how about throw a error

### LINKED ISSUE #94: invoke() promise never resolves
I have been having an intermittent issue in my application.  Very difficult to find but I believe I have tracked down the issue to what seems to be a bug in this module.

The problem lies in the `_write` method of `ShellStreamBuffer`, in [lib/utils.js](https://github.com/rannn505/node-powershell/blob/master/lib/utils.js#L23):

```
    if(chunk.compare(this.EOI) === 0) {
      cb();
      return this.emit('EOI');
    }
```

This code seems to assume that the EOI "signal" will be the entire chunk.  Based on my understanding of how streams work (and my testing), this is a faulty assumption.  If multiple invocations happen in quick succession, or if the invoked commands output to stdout, the chunk may look something like this:

```
output from script
another line from the script
EOI_<random string>
```

in cases like this, the EOI signal will not be recognized, and the promise returned by `invoke()` will never resolve.

I have worked around this problem by making two changes.

1) in [lib/shell.js](https://github.com/rannn505/node-powershell/blob/master/lib/Shell.js#L199), update the `invoke()` method so that the EOI signal is output on it's own line.
2) in [lib/utils.js](https://github.com/rannn505/node-powershell/blob/master/lib/utils.js#L23), update the logic in `_write()` to first break the chunk into lines and compare each line individually.

the first part is simple.  just replace 
```
      .then(() => shellSafeWrite(this.streams.stdin, `[Console]::Out.Write("${EOI}")`))
```
with this:

```
      .then(() => shellSafeWrite(this.streams.stdin, `[Console]::Out.WriteLine("");[Console]::Out.WriteLine("${EOI}")`))
```

The second step is slightly more complicated.  We need to change a few things.

in the constructor, define a buffer that will hold the (possibly incomplete) last line of output

```    this.lastLine = Buffer.from([]);```

and we need to update `_write` to be the following:

```
  _write(chunk, encoding, cb) {
    var tailBuf = Buffer.concat([this.lastLine, chunk]);  // include data from the last line of the previous chunk
    var lines = splitBuffer(tailBuf, EOL_BUFFER), line; // split the buffer by os.EOL
    while (lines.length > 1) { // for each line of the output
      line = lines.shift();
      if (line.compare(this.EOI) === 0) { // check if it matches our EOI signal
        cb();
        return this.emit('EOI');
      } else {
        this.chunksArray.push(line, EOL_BUFFER) // if not EOI signal, add it to the output.
      }
    }
    this.lastLine = lines[0];  // the last item is a possibly incomplete line of output, so we store it until we receive the next chunk
    return cb();
  }
```

definitions used by `_write`:

```
const EOL_BUFFER = Buffer.from(os.EOL);
function splitBuffer (buf, delim) {
  var search = -1,
    chunks = [],
    move = delim.length;

  while ((search = buf.indexOf(delim)) > -1) {
    chunks.push(buf.slice(0, search));
    buf = buf.slice(search + move);
  }

  chunks.push(buf);

  return chunks;
}
```

### LINKED ISSUE #96: Callback/EOI never returns
I have a similar problem to #94 where invoke() does not return. The problem is intermittant. In my application I have 4 instances of a Vue component which each instantiate their own `Shell` and call `Get-Service`. As you can see below, 3 of the 4 processes return whilst the 4th (PID 15456) does not. Repeat and only 2 return. About one in 10 times all 4 return.

Here's the code: https://github.com/cawoodm/powershell-servicemanager

image

Could it be that the EOI detection is shaky? How does it work exactly?

### PR DESCRIPTION
**Pull request by rannn505**
- Convert code base to Typescript
- Add .CONTIBUTE file to repo
- Improve library errors (fix #92)
- Fix invoke() promise never resolves bug (fix #94, fix #96)
- Fix MaxListenersExceededWarning (fix #84)
- Add support to inject environment variables via constructor options

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
Excited to see this!

**Comment by thakkarparth007** [comment]
Please merge this if it is ready!

**Comment by rannn505** [comment]
@TylerLeonhardt @thakkarparth007 expect it for next week :) it is going to be awesome!!

**Comment by sethlessard-innovia** [comment]
Excited for this!

**Comment by aminya** [comment]
Thanks for this awesome work! I am looking forward to using this.

**Comment by krystofwoldrich** [comment]
Hey, thanks for all the fixes and new features in this version. I hope soon a stable release of version 5 will be out.

But before that, I've found this error and solution for it, see the pull request https://github.com/rannn505/node-powershell/pull/123

**Comment by amt-work** [comment]
@rannn505 Is this going to be merged soon?

**Comment by rannn505** [comment]
@aminya I called it `nbsh` case `sh` is them most common abbreviation of shell (`node + sh(shell) = nbsh`) but I will consider it
@krystofwoldrich thx for bringing it 

@krystofwoldric
Thank you for bringing this to my attention. The truth is that the problem is quite simple to explain:
EOL marker in Windows is `/r/n`, and on Unix only `/n`, due to line 3 /n chars are not deleted on Windows which leads to the erros.
image
A better solution will be:
```js
const bn = /n.charCodeAt(0);
const br = /r.charCodeAt(0);
const space = ' '.charCodeAt(0);
export const isWhitespaceByte = (byte: number): boolean => byte === bn || byte === br || byte === space;
```
Can you change your PR and I will merge it?

@amt-work 
The epidemic caused me a long delay, I'm back to work on the new version today, hoping I can release it later this week.
The things left are mostly tests, documentation and examples.
Hope you understand the delay and thanks for the patient :)

**Comment by krystofwoldrich** [comment]
@rannn505 
Changed it, thanks, your solution is much nicer, I haven't realized it when doing the fix the first time.

It's ready to be merged. https://github.com/rannn505/node-powershell/pull/123

**Comment by rannn505** [comment]
Hey @everyone,

I'm sorry it takes me a while to release the new version, there are still a few things I need to finish for it to be completely ready (mostly documentation and unit testing) and the Corona period brings with it some unexpected issues 😞 

I plan at most to release it by the end of the month, thanks for the patience and good health to everyone 🙏

**Comment by Lundberg-Seth** [comment]
Any updates by chance? I'm hung up on a couple of these issues.

Appreciate all your work! It's a great package.

**Comment by rannn505** [comment]
@Lundberg-Seth It is going to be released by the end of next week, this time for real 🚀

**Comment by krystofwoldrich** [comment]
> @Lundberg-Seth It is going to be released by the end of next week, this time for real 🚀

That would be awesome. I'm also waiting for it. It'll be a blast.

**Comment by Lundberg-Seth** [comment]
Any updates? Thanks again!

**Comment by DarkLite1** [comment]
It would be great if this could be merged. It seems to solve a lot of issues.
Thank you for the great work.

**Comment by krystofwoldrich** [comment]
Hi, hope you're doing well, what's missing for the release?

Any way I could help?

**Comment by ahmad-invozone** [comment]
@rannn505 When you would be able to merge this?

Facing many issues in v4. Few of them are already mentioned in this pull request:

- (could not handle error event which emit under constructor. #92)
- (invoke() promise never resolves #94, fix Callback/EOI never returns #96)
- (MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit #84)

**Comment by rannn505** [comment]
Hi all, 

I'm sorry the new version has been delayed so long. I've been very busy, so it's mostly time that I'm lacking to finish it.
Most of the code is written, but I still need to work on the examples and documentation since the library went through a complete rewrite and a lot of new and different things have been added.
I promise I'm going to do my best to get something preliminary so you can help me keep going.
In a month or two, I'll be able to approach it with a fresh, positive mind, as I usually do when writing open source.

Please accept my sincerest thanks for your patience and trust in me. I promise it will pay off, as I have a bunch of cool features up my sleeve. 🙏🏽

**Comment by davidhagen** [comment]
Hello @rannn505 . I hope all well. Any news of releasing latest version! Thank you for your hard work.

**Comment by rannn505** [comment]
Hi @davidhagen . I will be back to work on it this week, and I believe the version will be ready by September 1st.

**Comment by netmastan** [comment]
Thank you. I'm getting the following error
I'm trying to restart machines and randomly getting the following error
`
		case"restart":
		ps.addCommand(`$GetProcessJob = Start-Job -FilePath "scripts\\restart.ps1" -Arg ${server},${vmname},${taskid}`);
          ps.addCommand(`Wait-Job $GetProcessJob | Out-Null`);
          ps.addCommand(`Receive-Job -Job $GetProcessJob`);		
		ps.invoke() //master.js 105
		.then(output => {
			res.send(output);
			ps.dispose();
		 })
		 .catch(err => {
		    res.status(500).send(responseResult({'code': 500,'status':1, 'message': err.message}));
			ps.dispose();
		 });
		break;`

`"stack": [
    "Error [ERR_STREAM_WRITE_AFTER_END]: write after end",
    "    at writeAfterEnd (_stream_writable.js:266:14)",
    "    at Socket.Writable.write (_stream_writable.js:315:5)",
    "    at c:\\Scripts\\myapp\\node_modules\\node-powershell\\lib\\utils.js:45:14",
    "    at new Promise (<anonymous>)",
    **"    at shellSafeWrite (c:\\Scripts\\myapp\\node_modules\\node-powershell\\lib\\utils.js:44:41)",
    "    at Shell.invoke (c:\\Scripts\\myapp\\node_modules\\node-powershell\\lib\\Shell.js:188:5)",**
    "    at c:\\Scripts\\myapp\\routes\\master.js:105:6",
    "    at newFn (c:\\Scripts\\myapp\\node_modules\\express-async-errors\\index.js:16:20)",
    "    at Layer.handle [as handle_request] (c:\\Scripts\\myapp\\node_modules\\express\\lib\\router\\layer.js:95:5)",
    "    at next (c:\\Scripts\\myapp\\node_modules\\express\\lib\\router\\route.js:137:13)",
    "    at Route.dispatch (c:\\Scripts\\myapp\\node_modules\\express\\lib\\router\\route.js:112:3)",
    "    at newFn (c:\\Scripts\\myapp\\node_modules\\express-async-errors\\index.js:16:20)",
    "    at Layer.handle [as handle_request] (c:\\Scripts\\myapp\\node_modules\\express\\lib\\router\\layer.js:95:5)",
    "    at c:\\Scripts\\myapp\\node_modules\\express\\lib\\router\\index.js:281:22",
    "    at Function.process_params (c:\\Scripts\\myapp\\node_modules\\express\\lib\\router\\index.js:335:12)",
    "    at next (c:\\Scripts\\myapp\\node_modules\\express\\lib\\router\\index.js:275:10)"
  ],
  "level": "error",
  "message": "uncaughtException: write after end",
  "timestamp": "2021-08-16T04:12:03.026Z"`

**Comment by braden-wallace** [comment]
Any update on when this branch may be complete/merged in? @rannn505 thanks for the hard work!

**Comment by rannn505** [comment]
Hi everybody,

Thanks for your patience, the current branch has been merged and released to npm as 5.0.0. 🚀 
There is still work to be done on tests, documentation, examples, and roadmap building. I am currently working on those and will release them as soon as possible.
Meanwhile, you can check out the new API [at the playground](https://github.com/rannn505/node-powershell/blob/master/playground/index.ts). ⛳ 
Please let me know your initial thoughts and any suggestions you may have. 💡 

Once again, thank you for your care, 🙏🏽 
Ran

**Pull request merged**
